"""Writes the Korean public holiday tables used by the app and the shared web page.

    python3 -m pip install holidays && python3 jelly-calendar/tools/make_holidays.py

Source: the "holidays" package (South Korea: lunar holidays, substitute holidays, election days
and temporary holidays as announced). Run again when the government adds a holiday.
"""
import datetime
import pathlib

import holidays

FIRST, LAST = 2025, 2030
ROOT = pathlib.Path(__file__).resolve().parents[2]
KOTLIN = ROOT / 'jelly-calendar/core/src/main/kotlin/io/github/ckdgus6068/jellycalendar/core/KoreanHolidays.kt'
WEB = ROOT / 'docs/share/holidays.js'

# Short labels for a calendar cell; the full name is shown where there is room.
SHORT = {
    '신정연휴': '신정',
    '설날 전날': '설날',
    '설날': '설날',
    '설날 다음날': '설날',
    '추석 전날': '추석',
    '추석': '추석',
    '추석 다음날': '추석',
    '기독탄신일': '성탄절',
    '대통령 선거일': '대선',
    '국회의원 선거일': '총선',
    '지방선거일': '지방선거',
    '임시공휴일': '임시휴일',
}
FULL = {
    '신정연휴': '신정',
    '기독탄신일': '성탄절',
}


def label(name):
    parts = [p.strip() for p in name.split(';')]
    if any('대체 휴일' in p for p in parts):
        return '대체공휴일', '대체휴일'
    full = '·'.join(FULL.get(p, p) for p in parts)
    short = SHORT.get(parts[0], parts[0])
    return full, short


def main():
    kr = holidays.KR(years=range(FIRST, LAST + 1), language='ko')
    rows = []
    for day, name in sorted(kr.items()):
        full, short = label(name)
        rows.append((day.isoformat(), full, short))
    stamp = f'holidays {holidays.__version__}, {datetime.date.today().isoformat()}'

    kotlin_rows = '\n'.join(f'        "{d}|{f}|{s}",' for d, f, s in rows)
    KOTLIN.write_text(f'''package io.github.ckdgus6068.jellycalendar.core

import java.time.LocalDate

// Generated by jelly-calendar/tools/make_holidays.py ({stamp}). Do not edit by hand.

/** A public holiday in Korea: its full name, and a short one for a calendar cell. */
data class Holiday(val name: String, val short: String)

/** Korean public holidays from {FIRST} to {LAST}, including substitute and election days. */
object KoreanHolidays {{
    val firstYear = {FIRST}
    val lastYear = {LAST}

    private val table: Map<LocalDate, Holiday> = listOf(
{kotlin_rows}
    ).associate {{ row ->
        val (date, name, short) = row.split('|')
        LocalDate.parse(date) to Holiday(name, short)
    }}

    fun on(date: LocalDate): Holiday? = table[date]
}}
''', encoding='utf-8')

    web_rows = '\n'.join(f"  ['{d}', '{f}', '{s}']," for d, f, s in rows)
    WEB.write_text(f'''// Generated by jelly-calendar/tools/make_holidays.py ({stamp}). Do not edit by hand.
// Korean public holidays from {FIRST} to {LAST}, including substitute and election days:
// [date, full name, short name for a calendar cell].
const ROWS = [
{web_rows}
];

const TABLE = new Map(ROWS.map(([date, name, short]) => [date, {{ name, short }}]));

/** The holiday on an ISO day ("2026-10-03"), or undefined. */
export function holidayOn(iso) {{
  return TABLE.get(iso);
}}
''', encoding='utf-8')
    print(f'{len(rows)} holidays, {FIRST}-{LAST}')


if __name__ == '__main__':
    main()
