// Writes the jelly characters of looks-src.mjs for the web (docs/share/looks.js) and for the app
// (core LookBook.kt), so both draw the same shapes. With --check it only says whether the written
// files are up to date (CI runs it that way).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LOOKS } from './looks-src.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const WEB = resolve(root, 'docs/share/looks.js');
const KOTLIN = resolve(root, 'jelly-calendar/core/src/main/kotlin/io/github/ckdgus6068/jellycalendar/core/LookBook.kt');

const ON = new Set(['head', 'face', 'body', 'back']);
const COLOR = /^(#[0-9A-F]{6}|body|shade|light)$/i;
const PATH = /^(?:[MLQCZ](?: -?\d+(?:\.\d+)?)*)(?: [MLQCZ](?: -?\d+(?:\.\d+)?)*)*$/;

function checkPart(part, where) {
  if (!PATH.test(part.d)) throw new Error(`${where}: path data ${part.d.slice(0, 40)}`);
  if (!part.fill && !part.stroke) throw new Error(`${where}: neither fill nor stroke`);
  for (const key of ['fill', 'stroke']) if (part[key] && !COLOR.test(part[key])) throw new Error(`${where}: ${key} ${part[key]}`);
  if (part.on && !ON.has(part.on)) throw new Error(`${where}: on ${part.on}`);
}

for (const [name, parts] of Object.entries(LOOKS.faces)) parts.forEach((p, i) => checkPart(p, `face ${name} #${i}`));
for (const job of LOOKS.jobs) {
  if (job.variants.length !== LOOKS.variantFaces.length) throw new Error(`${job.id}: ${job.variants.length} variants`);
  job.variants.forEach((parts, v) => parts.forEach((p, i) => checkPart(p, `${job.id} ${v} #${i}`)));
}

const web = `// Generated by jelly-calendar/share/looks/build-looks.mjs from looks-src.mjs. Do not edit.
// The jelly characters: see looks-src.mjs for what the parts mean.
export const LOOKS = ${JSON.stringify(LOOKS)};
`;

const kstr = (s) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const kfloat = (n) => `${Number.isInteger(n) ? `${n}.0` : n}f`;

function kpart(p) {
  const args = [kstr(p.d)];
  if (p.fill) args.push(`fill = ${kstr(p.fill)}`);
  if (p.stroke) args.push(`stroke = ${kstr(p.stroke)}`);
  if (p.stroke && p.width != null) args.push(`width = ${kfloat(p.width)}`);
  if (p.alpha != null) args.push(`alpha = ${kfloat(p.alpha)}`);
  if (p.on) args.push(`on = LookLayer.${p.on.toUpperCase()}`);
  return `LookPart(${args.join(', ')})`;
}

const kparts = (parts, indent) => (parts.length
  ? `listOf(\n${parts.map((p) => `${indent}    ${kpart(p)},`).join('\n')}\n${indent})`
  : 'emptyList()');

const kotlin = `// Generated by jelly-calendar/share/looks/build-looks.mjs from looks-src.mjs. Do not edit.
package io.github.ckdgus6068.jellycalendar.core

/** Where a part of a jelly character goes (see looks-src.mjs). */
enum class LookLayer { HEAD, FACE, BODY, BACK }

/**
 * One shape of a jelly character, in units of the jelly's radius (100 = the radius, y down).
 * [fill] and [stroke] are colours, or "body", "shade" and "light" for the jelly's own colour.
 */
data class LookPart(
    val d: String,
    val fill: String? = null,
    val stroke: String? = null,
    val width: Float = 4f,
    val alpha: Float = 1f,
    val on: LookLayer = LookLayer.HEAD,
)

/** A job with its outfits, one per face (variant). */
class LookJob(val id: String, val name: String, val variants: List<List<LookPart>>)

/** Every jelly character, the same as the shared page's (docs/share/looks.js). */
object LookBook {
    /** The face of each variant: 0 smiles with round eyes, 1 beams with its eyes shut. */
    val variantFaces: List<String> = listOf(${LOOKS.variantFaces.map(kstr).join(', ')})

    val faces: Map<String, List<LookPart>> by lazy {
        mapOf(
${Object.entries(LOOKS.faces).map(([name, parts]) => `            ${kstr(name)} to ${kparts(parts, '            ')},`).join('\n')}
        )
    }

    val jobs: List<LookJob> by lazy {
        listOf(
${LOOKS.jobs.map((job) => `            ${jobFun(job.id)}(),`).join('\n')}
        )
    }

    fun job(id: String): LookJob? = jobs.firstOrNull { it.id == id }
${LOOKS.jobs.map((job) => `
    private fun ${jobFun(job.id)}() = LookJob(
        ${kstr(job.id)},
        ${kstr(job.name)},
        listOf(
${job.variants.map((parts) => `            ${kparts(parts, '            ')},`).join('\n')}
        ),
    )`).join('\n')}
}
`;

function jobFun(id) {
  return `job${id[0].toUpperCase()}${id.slice(1)}`;
}

if (process.argv.includes('--check')) {
  const stale = [[WEB, web], [KOTLIN, kotlin]].filter(([file, text]) => {
    try {
      return readFileSync(file, 'utf8') !== text;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(`Out of date, run node jelly-calendar/share/looks/build-looks.mjs: ${stale.map(([f]) => f).join(', ')}`);
    process.exit(1);
  }
  console.log('looks up to date');
} else {
  writeFileSync(WEB, web);
  writeFileSync(KOTLIN, kotlin);
  const parts = LOOKS.jobs.reduce((n, j) => n + j.variants.reduce((m, v) => m + v.length, 0), 0);
  console.log(`wrote ${LOOKS.jobs.length} jobs, ${parts} parts: ${WEB} (${web.length} bytes), ${KOTLIN} (${kotlin.length} bytes)`);
}
